
# html lang
language: ja

# main menu navigation
menu:
  Home: /
  About: /about

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Noto+Sans+JP # for font
- https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css # for toc basic style

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  Twitter: https://twitter.com/ayasamind
  Github: https://github.com/ayasamind
  # and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
# archives: false
# categories: false
tags: false

# theme color
main_color: sea # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: UA-171683719-1

# commend module
comment:
  enable: false
  appId: your-app-id
  appKey: your-app-key
  placeholder: say something
  notify: false
  verify: false
  avatar: mp
